# from test_create_pr import test_create_pr
from test_playwright.test_create_pr import test_create_pr
from test_playwright.test_create_receipt import test_create_receipt
from test_playwright.test_invoice_legacy import test_invoice_legacy

test_create_pr()
test_create_receipt()
test_invoice_legacy()