from playwright.sync_api import Page, sync_playwright
import time


def test_create_contract_worspace():
    with sync_playwright() as playwright:
        browser = playwright.chromium.launch(headless=False)
        context = browser.new_context()
        page = context.new_page()
        page.goto("https://s1.au.cloud.ariba.com/Buyer/Main/ad/loginPage/SSOActions?awsso_cc=cmVhbG06VUZKRlRVbExRVlJKTFVSRlRVOUVVMEZRVUMweExWUT07YXdzc29fcnU6YUhSMGNITTZMeTl6TVM1aGRTNWpiRzkxWkM1aGNtbGlZUzVqYjIwdlFuVjVaWEl2VFdGcGJpOWhaQzlrWldaaGRXeDBMMFJwY21WamRFRmpkR2x2Ymo5eVpXRnNiVDFRVWtWTlNVdEJWRWt0UkVWTlQwUlRRVkJRTFRFdFZBPT07YXdzc29fbHU6YUhSMGNITTZMeTl6TVM1aGRTNWpiRzkxWkM1aGNtbGlZUzVqYjIwdlFuVjVaWEl2VFdGcGJpOWhaQzlqYkdsbGJuUk1iMmR2ZFhRdlUxTlBRV04wYVc5dWN3PT07YXdzc29fYXA6UW5WNVpYST07YXdzc29fYXJpZDpNVGN4TmpZeU1qazBOalU0TlE9PTthd3Nzb19rdTphSFIwY0hNNkx5OXpNUzVoZFM1amJHOTFaQzVoY21saVlTNWpiMjB2UW5WNVpYSXZUV0ZwYmk5aFpDOWpiR2xsYm5STFpXVndRV3hwZG1VdlUxTlBRV04wYVc5dWN3PT07YXdzc29fZmw6TVE9PQ%3D%3D%3AMegtIfsrz8OB62dn0rQZYiGAHao%3D&awsso_ap=Buyer&realm=PREMIKATI-DEMODSAPP-1-T&awsr=true#b0")
        page.get_by_role("textbox", name="User Name").fill("spaudel_prem_admin")
        page.get_by_text("Password", exact=True).click()
        page.get_by_role("textbox", name="Password").fill("Iam@Panda123")
        page.get_by_role("button", name="Sign In").click()
        time.sleep(3)
        page.locator('a[role="button"][aria-haspopup="menu"][id="_e80f4b"]').click() # Create button clicked.
        time.sleep(3)
        page.locator("//a[@id='_owurqd']").click()
        print("Contract Workspace (Procurement) clicked")
        page.get_by_role("textbox", name="Name:").fill("Test Contract Workspace 02")
        page.get_by_role("textbox", name="Description:").click()
        page.get_by_role("textbox", name="Description:").fill("Test Description")
        page.locator("[id=\"_4svpp\"] label").filter(has_text="No").locator("label").click()
        page.get_by_role("combobox", name="Hierarchical Type:").locator("span").nth(1).click()
        page.locator("span.w-dropdown-selected#text__0p7vc").click()
        print("Agreement dropdown clicked")
        page.locator("div.w-dropdown-item", has_text="Stand-alone Agreement").click()
        print("Stand-alone agreement selected.")
        # page.locator("[id=\"_mhzfuc\"]").get_by_role("link").click()
        page.get_by_role("combobox", name="Supplier:").click()
        page.get_by_role("combobox", name="Supplier:").fill("Subash Banjade")
        page.get_by_role("combobox", name="Supplier:").press("Enter")
        page.get_by_role("textbox", name="Agreement Date:").click()
        page.locator("[id=\"_4svpp\"]").get_by_role("table").click()
        time.sleep(2)
        page.get_by_role("textbox", name="Agreement Date:").click()
        page.get_by_role("textbox", name="Agreement Date:").fill("03/07/2025")
        page.get_by_role("textbox", name="Agreement Date:").press("Enter")
        time.sleep(2)
        page.get_by_role("textbox", name="Effective Date:").click()
        page.get_by_role("textbox", name="Effective Date:").fill("03/14/2025")
        page.get_by_role("textbox", name="Effective Date:").press("Enter")
        # page.locator("[id=\"_7dxkfb\"]").get_by_role("cell").filter(has_text=re.compile(r"^$")).click()
        time.sleep(2)
        page.get_by_role("textbox", name="Expiration Date:").click()
        page.get_by_role("textbox", name="Expiration Date:").fill("03/14/2025")
        page.get_by_role("textbox", name="Expiration Date:").press("Enter")
        page.get_by_role("textbox", name="Notice Period(in days):").click()
        page.get_by_role("textbox", name="Notice Period(in days):").click()
        page.get_by_role("textbox", name="Notice Period(in days):").fill("30")
        page.get_by_role("cell", name="Agreement Date: 03/07/2025 Select Date Term Type: * Effective Date: * 03/14/2025 Select Date Expiration Date: 03/14/2025 Select Date Notice Period(in days): 30", exact=True).click()
        page.get_by_role("textbox", name="Proposed Contract Amount (Non").click()
        page.get_by_role("textbox", name="Proposed Contract Amount (Non").fill("20000")
        page.get_by_role("textbox", name="Contract Amount (Fixed/").click()
        page.get_by_role("textbox", name="Contract Amount (Fixed/").fill("20000")
        page.get_by_role("combobox", name="Commodity:").click()
        page.get_by_role("combobox", name="Commodity:").fill("Drugs and Pharmaceutical Products 51")
        page.get_by_role("combobox", name="Commodity:").press("Enter")
        page.get_by_role("textbox", name="Name:").click()
        page.get_by_role("textbox", name="Name:").fill("Test Contract 11")
        page.get_by_role("button", name="Create").first.click()

